CREATE DATABASE `snippet`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

GRANT SELECT, SHOW VIEW ON `snippet`.* TO 'codex_robot'@'%';

CREATE TABLE `SNIPPET_USER` (
  `SNIPPET_USER_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '스니펫 사용자 번호',
  `GOOGLE_SUB` VARCHAR(100) NOT NULL COMMENT '구글 계정 고유 식별자',
  `EMAIL` VARCHAR(191) NOT NULL COMMENT '이메일',
  `USER_NM` VARCHAR(100) NOT NULL COMMENT '사용자명',
  `PROFILE_IMG_URL` VARCHAR(500) DEFAULT NULL COMMENT '프로필 이미지 URL',
  `LAST_LOGIN_DT` DATETIME DEFAULT NULL COMMENT '마지막 로그인 일시',
  `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
  `DEL_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
  `REG_NO` BIGINT DEFAULT NULL COMMENT '등록자 번호',
  `REG_DT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UDT_NO` BIGINT DEFAULT NULL COMMENT '수정자 번호',
  `UDT_DT` TIMESTAMP NULL DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`SNIPPET_USER_NO`),
  UNIQUE KEY `UK_SNIPPET_USER_01` (`GOOGLE_SUB`),
  KEY `IDX_SNIPPET_USER_01` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='스니펫 전용 사용자';

CREATE TABLE `SNIPPET_LANGUAGE` (
  `LANGUAGE_CD` VARCHAR(30) NOT NULL COMMENT '언어 코드',
  `LANGUAGE_NM` VARCHAR(50) NOT NULL COMMENT '언어명',
  `EDITOR_MODE` VARCHAR(50) NOT NULL COMMENT '에디터 모드명',
  `SORT_SEQ` INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
  `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
  `REG_NO` BIGINT DEFAULT NULL COMMENT '등록자 번호',
  `REG_DT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UDT_NO` BIGINT DEFAULT NULL COMMENT '수정자 번호',
  `UDT_DT` TIMESTAMP NULL DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='스니펫 언어 마스터';

CREATE TABLE `SNIPPET_FOLDER` (
  `FOLDER_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '폴더 번호',
  `SNIPPET_USER_NO` BIGINT NOT NULL COMMENT '스니펫 사용자 번호',
  `FOLDER_NM` VARCHAR(60) NOT NULL COMMENT '폴더명',
  `COLOR_HEX` VARCHAR(20) DEFAULT NULL COMMENT '폴더 색상 HEX',
  `SORT_SEQ` INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
  `DEL_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
  `REG_NO` BIGINT DEFAULT NULL COMMENT '등록자 번호',
  `REG_DT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UDT_NO` BIGINT DEFAULT NULL COMMENT '수정자 번호',
  `UDT_DT` TIMESTAMP NULL DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`FOLDER_NO`),
  UNIQUE KEY `UK_SNIPPET_FOLDER_01` (`SNIPPET_USER_NO`, `FOLDER_NM`, `DEL_YN`),
  KEY `IDX_SNIPPET_FOLDER_01` (`SNIPPET_USER_NO`, `SORT_SEQ`),
  CONSTRAINT `FK_SNIPPET_FOLDER_01`
    FOREIGN KEY (`SNIPPET_USER_NO`) REFERENCES `SNIPPET_USER` (`SNIPPET_USER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자별 스니펫 폴더';

CREATE TABLE `SNIPPET_TAG` (
  `TAG_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '태그 번호',
  `SNIPPET_USER_NO` BIGINT NOT NULL COMMENT '스니펫 사용자 번호',
  `TAG_NM` VARCHAR(60) NOT NULL COMMENT '태그명',
  `COLOR_HEX` VARCHAR(20) DEFAULT NULL COMMENT '태그 색상 HEX',
  `SORT_SEQ` INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
  `DEL_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
  `REG_NO` BIGINT DEFAULT NULL COMMENT '등록자 번호',
  `REG_DT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UDT_NO` BIGINT DEFAULT NULL COMMENT '수정자 번호',
  `UDT_DT` TIMESTAMP NULL DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`TAG_NO`),
  UNIQUE KEY `UK_SNIPPET_TAG_01` (`SNIPPET_USER_NO`, `TAG_NM`, `DEL_YN`),
  KEY `IDX_SNIPPET_TAG_01` (`SNIPPET_USER_NO`, `SORT_SEQ`),
  CONSTRAINT `FK_SNIPPET_TAG_01`
    FOREIGN KEY (`SNIPPET_USER_NO`) REFERENCES `SNIPPET_USER` (`SNIPPET_USER_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='사용자별 스니펫 태그';

CREATE TABLE `SNIPPET_BASE` (
  `SNIPPET_NO` BIGINT NOT NULL AUTO_INCREMENT COMMENT '스니펫 번호',
  `SNIPPET_USER_NO` BIGINT NOT NULL COMMENT '스니펫 사용자 번호',
  `FOLDER_NO` BIGINT DEFAULT NULL COMMENT '폴더 번호',
  `LANGUAGE_CD` VARCHAR(30) NOT NULL COMMENT '언어 코드',
  `TITLE` VARCHAR(150) NOT NULL COMMENT '스니펫 제목',
  `SUMMARY` VARCHAR(500) DEFAULT NULL COMMENT '스니펫 요약',
  `SNIPPET_BODY` MEDIUMTEXT NOT NULL COMMENT '스니펫 본문 코드',
  `MEMO` TEXT DEFAULT NULL COMMENT '추가 메모',
  `IS_FAVORITE` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '즐겨찾기 여부',
  `LAST_COPIED_DT` DATETIME DEFAULT NULL COMMENT '마지막 복사 일시',
  `DEL_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
  `REG_NO` BIGINT DEFAULT NULL COMMENT '등록자 번호',
  `REG_DT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  `UDT_NO` BIGINT DEFAULT NULL COMMENT '수정자 번호',
  `UDT_DT` TIMESTAMP NULL DEFAULT NULL COMMENT '수정 일시',
  PRIMARY KEY (`SNIPPET_NO`),
  KEY `IDX_SNIPPET_BASE_01` (`SNIPPET_USER_NO`, `DEL_YN`, `UDT_DT`),
  KEY `IDX_SNIPPET_BASE_02` (`SNIPPET_USER_NO`, `FOLDER_NO`, `DEL_YN`),
  KEY `IDX_SNIPPET_BASE_03` (`SNIPPET_USER_NO`, `LANGUAGE_CD`, `DEL_YN`),
  KEY `IDX_SNIPPET_BASE_04` (`SNIPPET_USER_NO`, `IS_FAVORITE`, `DEL_YN`, `UDT_DT`),
  KEY `IDX_SNIPPET_BASE_05` (`SNIPPET_USER_NO`, `TITLE`),
  CONSTRAINT `FK_SNIPPET_BASE_01`
    FOREIGN KEY (`SNIPPET_USER_NO`) REFERENCES `SNIPPET_USER` (`SNIPPET_USER_NO`),
  CONSTRAINT `FK_SNIPPET_BASE_02`
    FOREIGN KEY (`FOLDER_NO`) REFERENCES `SNIPPET_FOLDER` (`FOLDER_NO`),
  CONSTRAINT `FK_SNIPPET_BASE_03`
    FOREIGN KEY (`LANGUAGE_CD`) REFERENCES `SNIPPET_LANGUAGE` (`LANGUAGE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='스니펫 기본 정보';

CREATE TABLE `SNIPPET_TAG_MAP` (
  `SNIPPET_NO` BIGINT NOT NULL COMMENT '스니펫 번호',
  `TAG_NO` BIGINT NOT NULL COMMENT '태그 번호',
  `REG_NO` BIGINT DEFAULT NULL COMMENT '등록자 번호',
  `REG_DT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록 일시',
  PRIMARY KEY (`SNIPPET_NO`, `TAG_NO`),
  KEY `IDX_SNIPPET_TAG_MAP_01` (`TAG_NO`, `SNIPPET_NO`),
  CONSTRAINT `FK_SNIPPET_TAG_MAP_01`
    FOREIGN KEY (`SNIPPET_NO`) REFERENCES `SNIPPET_BASE` (`SNIPPET_NO`),
  CONSTRAINT `FK_SNIPPET_TAG_MAP_02`
    FOREIGN KEY (`TAG_NO`) REFERENCES `SNIPPET_TAG` (`TAG_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='스니펫 태그 매핑';

INSERT INTO `SNIPPET_LANGUAGE`
(`LANGUAGE_CD`, `LANGUAGE_NM`, `EDITOR_MODE`, `SORT_SEQ`, `USE_YN`, `REG_NO`, `UDT_NO`)
VALUES
('plain_text', 'Plain Text', 'text', 1, 'Y', NULL, NULL),
('javascript', 'JavaScript', 'javascript', 2, 'Y', NULL, NULL),
('typescript', 'TypeScript', 'typescript', 3, 'Y', NULL, NULL),
('java', 'Java', 'java', 4, 'Y', NULL, NULL),
('sql', 'SQL', 'sql', 5, 'Y', NULL, NULL),
('json', 'JSON', 'json', 6, 'Y', NULL, NULL),
('html', 'HTML', 'html', 7, 'Y', NULL, NULL),
('css', 'CSS', 'css', 8, 'Y', NULL, NULL),
('markdown', 'Markdown', 'markdown', 9, 'Y', NULL, NULL);
